spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mymongocustomer

  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: h1tv5i4h4qcpiea03pf4cik4q
            scope : openid,email,profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/cognito"
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_NnkSmsgNk

      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_NnkSmsgNk
#logging:
#  level:
#    root: debug


