apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwtvalidator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jwtvalidator
  template:
    metadata:
      labels:
        app: jwtvalidator
    spec:
      containers:
        - name: jwtvalidator
          image: ghcr.io/deftsquad/jwt-validator:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8081"
      imagePullSecrets:
        - name: ghcr-secret
