name: Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with Jib
        run: mvn clean compile jib:build \
          -Djib.to.image=ghcr.io/deftsquad/customer_api_backend:latest \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}

#
#      - name: Setup AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#      - name: Install Terraform
#        uses: hashicorp/setup-terraform@v3
#
#      - name: Terraform Init
#        working-directory: ./terraform
#        run: terraform init
#
#      - name: Terraform Apply
#        working-directory: ./terraform
#        run: terraform apply -auto-approve -var-file="dev.tfvars"

#      - name: Update Kubeconfig
#        run: aws eks update-kubeconfig --region us-east-1 --name customer-api-dev
#
#      - name: Deploy to EKS
#        run: |
#          kubectl apply -f terraform/kubernetes/deployment.yaml
#          kubectl apply -f terraform/kubernetes/service.yaml
  
